Repository DTel-HQ/dtel, pull requests merged in 2021-05, with the labels that each got.

#280 docs: remove, as they have moved to another repo
  mkdocs.yml
  readthedocs/docs/Customer-Support-Guide.md
  readthedocs/docs/FAQ.md
  readthedocs/docs/Payment.md
  readthedocs/docs/Privacy.md
  readthedocs/docs/VIP-Numbers.md
  readthedocs/docs/index.md
  readthedocs/docs/translations.md
Labels: enhancement, finished

#283 Resolve: 282 add and change documentation
  .github/CONTRIBUTING.md
  README.md
Labels: documentation, finished

#290 docs: add .mailmap
  .mailmap
Labels: finished, meta

#291 update color of badges for new discord branding
  README.md
Labels: documentation, enhancement, finished
